source "https://rubygems.org"

gem 'rack'
gem "rack-contrib", require: "rack/contrib"
gem 'grape'
gem 'grape-reload'
gem 'grape-swagger'
gem 'activerecord', require: 'active_record'
gem 'grape-activerecord'
gem "pg"
gem 'rake'
