production:
  adapter: postgresql
  encoding: utf8
  database: trackit
  username: postgres
  password: Uk33p0u7
  pool: 5


development:
  adapter: postgresql
  encoding: utf8
  database: trackit
  username: postgres
  password: Uk33p0u7
  pool: 5
  host: localhost
  port: 5432